config/routes.rb
Kiosk::Application.routes.draw do
  devise_for :users
  resources :articles

  resources :magazine_pages

  resources :magazine_page_layouts

  resources :magazines

  root 'magazines#index'

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  validates :status, inclusion: { in: %w(DRAFT SUBMITTED REVIEW PUBLISHED) , message: "%{value} is not a valid status." }
  validates :title, :price, presence: true
  has_many :magazine_pages



end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]
  before_action :valid_status, only: [:new, :edit]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @magazine }
      else
        format.html { render action: 'new' }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:user, :title, :short_description, :long_description, :status, :price)
    end

  def valid_status
    @valid_status = %w(DRAFT SUBMITTED REVIEW PUBLISHED)
  end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.erb
<%= simple_form_for @magazine, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :short_description %>
  <%= f.input :long_description %>
  <%= f.input :status, :collection => @valid_status %>
  <%= f.input :price %>
  <div class="form-actions">
    <% unless @magazine.new_record? %>
        <%= link_to t('.edit', :default => t("helpers.links.addpage")),
                    new_magazine_page_path(:magazine_id => @magazine), :class => 'btn' %>
    <% end %>
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                magazines_path, :class => 'btn' %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<%- model_class = Magazine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/magazines/index.html.erb
<%- model_class = Magazine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= link_to magazine.title, magazine_path(magazine) %></td>
        <td><%= magazine.status %></td>
        <td><%= magazine.price %></td>
        <td><%=l magazine.created_at, format: :long %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_magazine_path(magazine), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      magazine_path(magazine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/magazines/new.html.erb
<%- model_class = Magazine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/magazines/show.html.erb
<%- model_class = Magazine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @magazine.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @magazine.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_description) %>:</strong></dt>
  <dd><%= @magazine.short_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:long_description) %>:</strong></dt>
  <dd><%= @magazine.long_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @magazine.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @magazine.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              magazines_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_magazine_path(@magazine), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              magazine_path(@magazine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>