config/routes.rb
Kiosk::Application.routes.draw do
  devise_for :users
  resources :articles

  resources :magazine_pages

  resources :magazine_page_layouts

  resources :magazines

  root 'magazines#index'

end

app/models/magazine_page.rb
class MagazinePage < ActiveRecord::Base
  belongs_to :magazine
  belongs_to :magazine_page_layout, :foreign_key => 'page_layout_id'
  has_many :articles

  validates :page, presence: true, numericality: true
  validates :magazine_id, presence: true
  validates :page_layout_id, presence: true
end

app/controllers/magazine_pages_controller.rb
class MagazinePagesController < ApplicationController
  before_action :set_magazine_page, only: [:show, :edit, :update, :destroy]
  before_action :set_magazine_page_layout, only: [:new, :edit]

  # GET /magazine_pages
  # GET /magazine_pages.json
  def index
    @magazine_pages = MagazinePage.all
  end

  # GET /magazine_pages/1
  # GET /magazine_pages/1.json
  def show
  end

  # GET /magazine_pages/new
  def new
    @magazine_page = MagazinePage.new
    @magazine = Magazine.find(params[:magazine_id])
    @magazine_page.magazine = @magazine
  end

  # GET /magazine_pages/1/edit
  def edit
  end

  # POST /magazine_pages
  # POST /magazine_pages.json
  def create
    @magazine_page = MagazinePage.new(magazine_page_params)
    @magazine = Magazine.find(@magazine_page.magazine_id)
    @magazine_page.page = MagazinePage.where(magazine_id: @magazine_page.magazine_id).count + 1 # page will always be last for new magazine page
    respond_to do |format|
      if @magazine_page.save
        format.html { redirect_to @magazine_page, notice: 'Magazine page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @magazine_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @magazine_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazine_pages/1
  # PATCH/PUT /magazine_pages/1.json
  def update
    respond_to do |format|
      if @magazine_page.update(magazine_page_params)
        format.html { redirect_to @magazine_page, notice: 'Magazine page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @magazine_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazine_pages/1
  # DELETE /magazine_pages/1.json
  def destroy
    @magazine_page.destroy
    respond_to do |format|
      format.html { redirect_to magazine_pages_url }
      format.json { head :no_content }
    end
  end

  private
  def set_magazine_page_layout
    @magazine_page_layouts = MagazinePageLayout.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_magazine_page
    @magazine_page = MagazinePage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def magazine_page_params
    params.require(:magazine_page).permit(:page, :magazine_id, :page_layout_id)
  end
end

app/helpers/magazine_pages_helper.rb
module MagazinePagesHelper
end

app/views/magazine_pages/_form.html.erb
<%= simple_form_for @magazine_page, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :page_layout_id, :collection => @magazine_page_layouts %>
  <%= f.input :magazine_id, :as => 'hidden', :input_html => {:value => params[:magazine_id]} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                magazine_pages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/magazine_pages/edit.html.erb
<%- model_class = MagazinePage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<%= render template: '/magazine_page_layouts/' + @magazine_page.magazine_page_layout.template_file %>

app/views/magazine_pages/index.html.erb
<%- model_class = MagazinePage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:page) %></th>
      <th><%= model_class.human_attribute_name(:magazine_id) %></th>
      <th><%= model_class.human_attribute_name(:page_layout_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @magazine_pages.each do |magazine_page| %>
      <tr>
        <td><%= link_to magazine_page.id, magazine_page_path(magazine_page) %></td>
        <td><%= magazine_page.page %></td>
        <td><%= magazine_page.magazine_id %></td>
        <td><%= magazine_page.page_layout_id %></td>
        <td><%=l magazine_page.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_magazine_page_path(magazine_page), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      magazine_page_path(magazine_page),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_magazine_page_path,
            :class => 'btn btn-primary' %>

app/views/magazine_pages/new.html.erb
<%- model_class = MagazinePage -%>
<div class="page-header">
  <h1><%=t '.title', :default => ['%{magazine}'], :magazine => @magazine.title %></h1>
</div>
<%= render :partial => 'form' %>

app/views/magazine_pages/show.html.erb
<%- model_class = MagazinePage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:page) %>:</strong></dt>
  <dd><%= @magazine_page.page %></dd>
  <dt><strong><%= model_class.human_attribute_name(:magazine_id) %>:</strong></dt>
  <dd><%= @magazine_page.magazine.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_layout_id) %>:</strong></dt>
  <dd><%= @magazine_page.magazine_page_layout %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              magazine_pages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_magazine_page_path(@magazine_page), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              magazine_page_path(@magazine_page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>